export const FINE_TYPES = [
  "Conduct Unbecoming (§11-010)",
  "General Misconduct (§11-020)",
  "Misconduct Under Influence (§11-030)",
  "Missing Security at Function (§11-050)",
  "Missing Required Event (§11-060)",
  "Missing Recruitment/Work Week (§11-070)",
  "Removal/Damage to House Property (§11-080)",
  "Removal/Damage to Personal Property (§11-090)",
  "Missing Chapter Meeting (§11-100)",
  "Missing Exec Meeting (§11-110)",
  "Missing Yearbook/Composite (§11-120)",
  "Kitchen Duties (§11-130)",
  "House Clean (§11-140)",
  "Event House Clean (§11-150)",
  "Chores (§11-160)",
  "Missing Philanthropy Event (§11-170)",
  "Smoking (§11-190)",
  "Fire Alarm (§11-200)",
  "Drop Testing Cleanup (§11-210)",
  "Unauthorized Weapon Use (§11-220)",
  "Sexual Relations on Sleeping Porch (§11-230)",
  "Formal Dinner Attire (§11-240)",
  "Grazers (§11-250)",
  "Social Probation Violation (§11-260)",
  "Missing House Philanthropy Event (§11-270)",
  "Missing Signed-Up Philanthropy Event (§11-280)",
  "Bathroom Trash Violation (§11-290)",
  "Physical Violence (§11-300)",
  "Committee Meeting Absence (§7-005)",
  "Missing JP Meeting (§10-220)",
  "Cell Phone in Exec Meeting (§8-060)",
  "Grievance Committee No-Show (§7-030)",
  "Guest Misconduct (§12-030)",
  "Breathalyzer Misuse (§12-080)",
  "Silent Sleeping Porch Violation (§18-350)",
  "Missing Blood Drive (§16-010)",
  "Missing Philanthropy Hours (§16-010)",
  "Vacant Room (§17-020)",
  "Room Improvement Removal (§17-240)",
  "Inadequate Room Space (§17-360)",
  "Failure to Vacate Room (§17-370)",
  "Other",
] as const;

export type FineType = (typeof FINE_TYPES)[number] | (string & {});

export const FINE_DEFAULT_AMOUNTS: Partial<Record<string, number>> = {
  "General Misconduct (§11-020)":                    10,
  "Misconduct Under Influence (§11-030)":             5,
  "Missing Security at Function (§11-050)":           25,
  "Missing Required Event (§11-060)":                 10,
  "Missing Recruitment/Work Week (§11-070)":          35,
  "Missing Chapter Meeting (§11-100)":                10,
  "Missing Exec Meeting (§11-110)":                   5,
  "Missing Yearbook/Composite (§11-120)":             25,
  "Kitchen Duties (§11-130)":                         35,
  "House Clean (§11-140)":                            10,
  "Event House Clean (§11-150)":                      10,
  "Chores (§11-160)":                                 10,
  "Missing Philanthropy Event (§11-170)":             5,
  "Smoking (§11-190)":                                25,
  "Fire Alarm (§11-200)":                             25,
  "Drop Testing Cleanup (§11-210)":                   1,
  "Unauthorized Weapon Use (§11-220)":                5,
  "Sexual Relations on Sleeping Porch (§11-230)":     10,
  "Formal Dinner Attire (§11-240)":                   5,
  "Grazers (§11-250)":                                5,
  "Social Probation Violation (§11-260)":             15,
  "Missing House Philanthropy Event (§11-270)":       50,
  "Missing Signed-Up Philanthropy Event (§11-280)":   25,
  "Bathroom Trash Violation (§11-290)":               5,
  "Physical Violence (§11-300)":                      15,
  "Committee Meeting Absence (§7-005)":               10,
  "Missing JP Meeting (§10-220)":                     15,
  "Cell Phone in Exec Meeting (§8-060)":              5,
  "Grievance Committee No-Show (§7-030)":             25,
  "Guest Misconduct (§12-030)":                       10,
  "Breathalyzer Misuse (§12-080)":                    10,
  "Silent Sleeping Porch Violation (§18-350)":        5,
  "Room Improvement Removal (§17-240)":               60,
  "Inadequate Room Space (§17-360)":                  10,
  "Failure to Vacate Room (§17-370)":                 5,
};

export const FINE_DESCRIPTIONS: Partial<Record<string, string>> = {
  "Conduct Unbecoming (§11-010)": "Conduct unbecoming a member of Acacia Fraternity",
  "General Misconduct (§11-020)": "General misconduct in violation of chapter standards",
  "Misconduct Under Influence (§11-030)": "Misconduct while under the influence of alcohol or substances",
  "Missing Security at Function (§11-050)": "Failed to fulfill assigned security duty at a chapter function",
  "Missing Required Event (§11-060)": "Failed to attend a required chapter event",
  "Missing Recruitment/Work Week (§11-070)": "Failed to participate in recruitment or work week",
  "Removal/Damage to House Property (§11-080)": "Removed or caused damage to house property",
  "Removal/Damage to Personal Property (§11-090)": "Removed or caused damage to another member's personal property",
  "Missing Chapter Meeting (§11-100)": "Failed to attend a required chapter meeting",
  "Missing Exec Meeting (§11-110)": "Failed to attend a required executive board meeting",
  "Missing Yearbook/Composite (§11-120)": "Failed to appear for yearbook or composite photo",
  "Kitchen Duties (§11-130)": "Failed to complete assigned kitchen duties",
  "House Clean (§11-140)": "Failed to participate in scheduled house clean",
  "Event House Clean (§11-150)": "Failed to participate in post-event house clean",
  "Chores (§11-160)": "Failed to complete assigned chores",
  "Missing Philanthropy Event (§11-170)": "Failed to attend a required philanthropy event",
  "Smoking (§11-190)": "Smoking in violation of chapter policy",
  "Fire Alarm (§11-200)": "Caused or contributed to a false fire alarm",
  "Drop Testing Cleanup (§11-210)": "Failed to assist with drop testing cleanup",
  "Unauthorized Weapon Use (§11-220)": "Unauthorized possession or use of a weapon on chapter property",
  "Sexual Relations on Sleeping Porch (§11-230)": "Violation of sleeping porch conduct policy",
  "Formal Dinner Attire (§11-240)": "Failed to meet formal dinner dress code requirements",
  "Grazers (§11-250)": "Eating outside of designated meal times without authorization",
  "Social Probation Violation (§11-260)": "Violated terms of active social probation",
  "Missing House Philanthropy Event (§11-270)": "Failed to attend a required house philanthropy event",
  "Missing Signed-Up Philanthropy Event (§11-280)": "Failed to attend a philanthropy event they signed up for",
  "Bathroom Trash Violation (§11-290)": "Left trash or violation of bathroom cleanliness standards",
  "Physical Violence (§11-300)": "Engaged in physical violence or threatening behavior",
  "Committee Meeting Absence (§7-005)": "Failed to attend an assigned committee meeting",
  "Missing JP Meeting (§10-220)": "Failed to appear at a scheduled JP meeting",
  "Cell Phone in Exec Meeting (§8-060)": "Used cell phone during an executive board meeting",
  "Grievance Committee No-Show (§7-030)": "Failed to appear before the grievance committee",
  "Guest Misconduct (§12-030)": "Guest caused misconduct or violated chapter rules",
  "Breathalyzer Misuse (§12-080)": "Misuse or tampering with chapter breathalyzer equipment",
  "Silent Sleeping Porch Violation (§18-350)": "Violated quiet hours policy on the sleeping porch",
  "Missing Blood Drive (§16-010)": "Failed to attend the required blood drive",
  "Missing Philanthropy Hours (§16-010)": "Failed to complete required philanthropy service hours",
  "Vacant Room (§17-020)": "Left room vacant without proper notification",
  "Room Improvement Removal (§17-240)": "Removed chapter-approved room improvements without authorization",
  "Inadequate Room Space (§17-360)": "Failed to maintain adequate room space per chapter standards",
  "Failure to Vacate Room (§17-370)": "Failed to vacate room by the required date",
  "Other": "",
};
